 import "@/app/globals.css"
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/src/components/Navbar'
import GetUser from '@/src/components/GetUser'
import GetAuth from '@/src/components/GetAuth'
import { ThemeProvider } from '@/components/theme-provider'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">  
      <body className='mx-auto h-screen justify-center items-center bg-slate-700'>
      <ClerkProvider> 
        
      <Navbar />  
        {children} 
        </ClerkProvider>
      </body>
    </html>
  
  )
}
 